# ADC chip registers
SIS3316_FPGA_ADC_GRP_REG_BASE	 = 0x1000
SIS3316_FPGA_ADC_GRP_REG_OFFSET	 = 0x1000

def SIS3316_ADC_GRP(reg, idx):
	''' Select FPGA's register space according to group index. '''
	return reg + SIS3316_FPGA_ADC_GRP_REG_BASE +\
				SIS3316_FPGA_ADC_GRP_REG_OFFSET * idx
					
INPUT_TAP_DELAY_REG 	= 0x00
ANALOG_CTRL_REG     	= 0x04
DAC_OFFSET_CTRL_REG 	= 0x08
SPI_CTRL_REG        	= 0x0C
EVENT_CONFIG_REG    	= 0x10
CHANNEL_HEADER_REG  	= 0x14
ADDRESS_THRESHOLD_REG 	= 0x18
TRIGGER_GATE_WINDOW_LENGTH_REG 	= 0x1C

RAW_DATA_BUFFER_CONFIG_REG 	= 0x20
PILEUP_CONFIG_REG     	= 0x24
PRE_TRIGGER_DELAY_REG 	= 0x28

DATAFORMAT_CONFIG_REG 	= 0x30
MAW_TEST_BUFFER_CONFIG_REG 	= 0x34
INTERNAL_TRIGGER_DELAY_CONFIG_REG 	= 0x38
INTERNAL_GATE_LENGTH_CONFIG_REG 	= 0x3C

SUM_FIR_TRIGGER_SETUP_REG	 = 0x80
SUM_FIR_TRIGGER_THRESHOLD_REG	 = 0x84
SUM_FIR_HIGH_ENERGY_THRESHOLD_REG	 = 0x88

TRIGGER_STATISTIC_COUNTER_MODE_REG	 = 0x90

ACCUMULATOR_GATE1_CONFIG_REG	 = 0xA0
ACCUMULATOR_GATE2_CONFIG_REG	 = 0xA4
ACCUMULATOR_GATE3_CONFIG_REG	 = 0xA8
ACCUMULATOR_GATE4_CONFIG_REG	 = 0xAC
ACCUMULATOR_GATE5_CONFIG_REG	 = 0xB0
ACCUMULATOR_GATE6_CONFIG_REG	 = 0xB4
ACCUMULATOR_GATE7_CONFIG_REG	 = 0xB8
ACCUMULATOR_GATE8_CONFIG_REG	 = 0xBC

FIRMWARE_REG 	= 0x100	# read only
STATUS_REG   	= 0x104	# read only
DAC_OFFSET_READBACK_REG = 0x108
SPI_READBACK_REG 	= 0x10C

# per-channel registers:
#offset is 0x10:
FIR_TRIGGER_SETUP_REG 	= 0x40
FIR_TRIGGER_THRESHOLD_REG 	= 0x44
FIR_HIGH_ENERGY_THRESHOLD_REG 	= 0x48

#offset is 0x4:
ACTUAL_SAMPLE_ADDRESS_REG 	= 0x110
PREVIOUS_BANK_SAMPLE_ADDRESS_REG 	= 0x120

